# Generated by Django 4.2.16 on 2024-10-19 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(blank=True, max_length=400, null=True)),
                ('skill2', models.CharField(blank=True, max_length=400, null=True)),
                ('skill3', models.CharField(blank=True, max_length=400, null=True)),
                ('skill4', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sslc', models.CharField(blank=True, max_length=200, null=True)),
                ('sslcmark', models.IntegerField(blank=True, null=True)),
                ('plustwo', models.CharField(blank=True, max_length=200, null=True)),
                ('plustwomark', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('degreemark', models.IntegerField(blank=True, null=True)),
                ('pg', models.CharField(blank=True, max_length=200, null=True)),
                ('pgmark', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_media')),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('relation', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience1', models.CharField(blank=True, max_length=900, null=True)),
                ('experience2', models.CharField(blank=True, max_length=900, null=True)),
                ('experience3', models.CharField(blank=True, max_length=900, null=True)),
                ('experience4', models.CharField(blank=True, max_length=900, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
